name: Push Workflow

on:
  push:
    branches: ["main"]

jobs:
  execute-test:
    runs-on: ubuntu-latest
    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: java --version  